#!/bin/bash
# Menu to maintain and build CM.
# Written by tristan202. Feel free to use, modify and distribute the script.
# Just remember to give proper credit
#
# tristan202 [ad] gmail.com

me=`basename $0`

# Colorize and add text parameters
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldgrn=${txtbld}$(tput setaf 2) #  green
bldblu=${txtbld}$(tput setaf 4) #  blue
txtrst=$(tput sgr0)             # Reset
line='----------------------------------------'

if [ "$#" == "0" ]; then
  echo ""
  echo "Usage: $me {Model name, i.e. yuga|maguro}"
  exit 1
fi

CM=$HOME/android/cm10.2
DEVICE=$1
OUT=$CM/out/target/product/$DEVICE
TRISTAN202=$HOME/android/tristan202

guake -r CM-10.2
numlockx on

Output() {
  echo "${bldgrn}$(date -d "1970-01-01 UTC $2 seconds") - $1 $OPERATION""ing $3${txtrst}"
}

Duration() {
  local S=$(echo $FINISH_TIME $BEGIN_TIME | awk '{print$1-$2}')
  ((h=S/3600))
  ((m=S%3600/60))
  ((s=S%60))
  printf "$OPERATION""ing took: %dh:%dm:%ds\n" $h $m $s
}

Begin() {
  BEGIN_TIME=$(date +%s)
  Output Begin $BEGIN_TIME "$1"
}

Finish() {
  FINISH_TIME=$(date +%s)
  Output Finished $FINISH_TIME "$1"
  Duration
}

Init_Repo ()
{
  clear
  if [ ! -d $CM ]; then
    echo ""
    echo "${bldblu}Setting up CM repo...${txtrst}"
    mkdir $CM
  fi
  if [ ! -d ~/bin ]; then
    mkdir ~/bin
    PATH=~/bin:$PATH
    curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
  fi
  if [ ! -f ~/bin/repo ]; then
    curl https://dl-ssl.google.com/dl/googlesource/git-repo/repo > ~/bin/repo
    chmod a+x ~/bin/repo
  fi
  cd $CM && repo init -u git://github.com/CyanogenMod/android.git -b cm-10.2
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Start_Sync ()
{
  clear
  if [ -d $CM ]; then
    echo ""
    OPERATION="Sync"
    echo "${bldblu}Syncing repo...${txtrst}"
    Begin
    echo ""
    cd $CM/frameworks/base && git stash
    cd $CM && repo sync
    cd $TRISTAN202/android_frameworks_base && cp -r * $CM/frameworks/base
    Finish
  else
    echo ""
    echo "${bldred}Directory does not exist. Check your 'CM' variable in line 5.${txtrst}"
    echo ""
    exit 0
  fi
  Sync_End
}

Sync_End ()
{
  echo ""
  echo "${bldblu}Got any cherries to pick?${txtrst}"
  echo -n "Press [${bldgrn}Y${txtrst}] if you do, or [${bldred}N${txtrst}] to return to main menu."
  echo ""
  read -n1 char
  case "$char" in
    [Nn]) Main ;;
    [Yy])  Pick_Cherries ;;
    *)   clear && echo "" && Sync_End ;;
  esac
}

Start_Build ()
{
  clear
  OPERATION="Build"
  files=$(ls $OUT/*.zip* 2> /dev/null | wc -l)
  if [ "$files" != "0" ]; then
    echo "${bldblu}Previous builds detected in 'out' folder. Delete them now?${txtrst}"
    echo -n "Press [${bldgrn}Y${txtrst}] to delete them, or [${bldred}N${txtrst}] to start build without deleting them."
    echo ""
    read -n1 char
    case "$char" in
      [Nn]) Build ;;
      [Yy])  rm $OUT/*.zip* ;;
      *) Start_Build ;;
    esac
  fi
  Build
}

Build ()
{
  clear
  echo ""
  echo "${bldblu}Good, starting build...${txtrst}"
  Begin
  if [ ! -f $CM/vendor/cm/proprietary/lib/armeabi/libjackpal-androidterm4.so ] && [ ! -f $CM/vendor/cm/proprietary/lib/mips/libjackpal-androidterm4.so ] && [ ! -f $CM/vendor/cm/proprietary/lib/x86/libjackpal-androidterm4.so ]; then
    $CM/vendor/cm/get-prebuilts
  fi
  cd $CM
  rm -rf out/target/product/$DEVICE/system/build.prop
  wait
  echo ""
  echo "${bldblu}Setting up environment${txtrst}"
  echo ""
  . build/envsetup.sh
  wait
  echo ""
  echo "${bldblu}Brunching device${txtrst}"
  echo ""
  brunch $DEVICE -j2
  Finish
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Reboot_Bootloader ()
{
  clear
  echo ""
  echo "${bldblu}Rebooting to bootloader. Happy flashing.${txtrst}"
  adb reboot bootloader
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Start_Clobber ()
{
  clear
  echo ""
  echo "${bldblu}Cleaning build directory...${txtrst}"
  OPERATION="Clean"
  Begin
  cd $CM
  make clobber
  Finish
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Pick_Cherries ()
{
  clear
  echo ""
  echo "${bldblu}Picking cherries...${txtrst}"
  OPERATION="Cherrypick"
  tput cnorm
  echo ""
  echo "${bldblu}Copy/paste the project folder, i.e. 'frameworks/base'${txtrst}"
  echo -n ">" && read folder
  echo ""
  echo "${bldblu}Now paste the cherry-pick git link, i.e. 'git fetch <someproject> refs/changes/... && git cherry-pick FETCH_HEAD'${txtrst}"
  echo -n ">" && read cherry
  clear
  echo ""
  Begin
  cd $CM/$folder
  CHERRY=${cherry%%??????????????????????????????}
  $CHERRY && git cherry-pick FETCH_HEAD
  Finish
  echo ""
  echo "${bldblu}Got any more cherries to pick?${txtrst}"
  echo -n "Press [${bldgrn}Y${txtrst}] if you do, or [${bldred}N${txtrst}] to return to main menu."
  echo ""
  read -n1 char
  case "$char" in
    [Nn]) Main ;;
    [Yy])  Pick_Cherries ;;
    *)   Pick_Cherries ;;
  esac
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Start_Push ()
{
  NOW=$(date +%b-%d-%Y)
  clear
  echo "If you haven't done so already, connect your phone to usb now."
  read -p "${bldblu}Press [Enter] to continue...${txtrst}"
  echo ""
  if pidof -x adb > /dev/null
  then
    echo "ADB server already running, proceeding."
    sleep 2
  else
    adb start-server
  fi
  DEVICES=$(adb get-state)
  if [ $DEVICES == "device" ]; then
    FILE=$(find $OUT -type f -name "cm-10.2*.zip" -printf %f)
    for zip in $FILE
    do
      echo "${bldblu}$line${txtrst}"
      echo ""
      echo "Push to internal or external?"
      echo ""
      echo "  ${bldblu}1${txtrst}    Internal (/sdcard)"
      echo "  ${bldblu}2${txtrst}    External (/ext_card)"
      echo ""
      echo "${bldblu}$line${txtrst}"
      echo -n "  "
      read -n1 answer
      case "$answer" in
        [1]) Push_Int ;;
        [2]) Push_Ext ;;
      esac
    done
  else
    echo ""
    echo "${bldred}Are you completely sure you remembered to plug in both ends of the cable?${txtrst}"
    read -p "${bldblu}Press [Enter] to try again...${txtrst}"
    Start_Push
  fi
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Push_Int ()
{
  FILE=$(find $OUT -type f -name "cm-10.2*.zip" -printf %f)
  for zip in $FILE
  do
    OPERATION="Push"
    Begin
    echo ""
    echo "Pushing '$zip' to /sdcard/cm-unofficial-$NOW-tristan202.zip"
    adb push $OUT/$zip /sdcard/cm-unofficial-$NOW-tristan202.zip
    Finish
  done
}

Push_Ext ()
{
  FILE=$(find $OUT -type f -name "cm-10.2*.zip" -printf %f)
  for zip in $FILE
  do
    OPERATION="Push"
    Begin
    echo ""
    echo "Pushing '$zip' to /ext_card/cm-unofficial-$NOW-tristan202.zip"
    adb push $OUT/$zip /ext_card/cm-unofficial-$NOW-tristan202.zip
    Finish
  done
}

Reboot_Recovery ()
{
  clear
  echo ""
  echo "${bldblu}Rebooting to recovery. Happy flashing.${txtrst}"
  adb reboot recovery
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Ask_Clobber ()
{
  while true
  do
    clear
    echo ""
    echo "${bldblu}Are you sure you want to do this? It is rarely needed...${txtrst}"
    echo ""
    echo -n "Press [${bldred}Y${txtrst}] to continue, or [${bldgrn}N${txtrst}] to return to main menu."
    read -n1 char
    case "$char" in
      [Nn]) Main ;;
      [Yy]) Start_Clobber ;;
      *) Ask_Clobber ;;
    esac
  done
}

Get_Prebuilts ()
{
  clear
  echo ""
  echo "${bldblu}Getting prebuilts. This only needs to be done once...${txtrst}"
  echo ""
  OPERATION="Gett"
  Begin
  $CM/vendor/cm/get-prebuilts
  Finish
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Logcat_Menu ()
{
  NOW=$(date +%b-%d-%Y-%H.%M)
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "Logcat menu"
    echo ""
    echo "To stop the logcat, press ctrl+z"
    echo "The name of the logfile will be"
    echo "~/logcat-<time-date>.log"
    echo ""
    echo "Select from the following functions"
    echo ""
    echo "  ${bldblu}1${txtrst}    Logcat to file"
    echo "  ${bldblu}2${txtrst}    Live logcat"
    echo "${bldblu}$line${txtrst}"
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [1]) clear && adb logcat >> ~/logcat-$NOW.log;;
      [2]) clear && adb logcat -C;;
    esac
  done
  exit 0
}

Reboot_Menu ()
{
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "Reboot menu"
    echo ""
    echo "Select from the following functions"
    echo ""
    echo "  ${bldblu}1${txtrst}    Reboot"
    echo "  ${bldblu}2${txtrst}    Reboot to recovery"
    echo "  ${bldblu}3${txtrst}    Reboot to bootloader"
    echo "  ${bldblu}4${txtrst}    Return to main menu"
    echo "${bldblu}$line${txtrst}"
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [1]) adb reboot && Main;;
      [2]) Reboot_Recovery;;
      [3]) Reboot_Bootloader;;
      [4]) Main;;
    esac
  done
  exit 0
}

Main ()
{
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "CM maintenance and build script"
    echo ""
    echo "Building ${bldblu}CM-10.2${txtrst} for ${bldblu}$DEVICE${txtrst}"
    echo ""
    echo "Select from the following functions"
    echo ""
    if [ ! -f $CM/.repo/manifest.xml ]; then
      echo "  ${bldgrn}S${txtrst}    Set up CM 10.2 repo"
    fi
    echo "  ${bldblu}1${txtrst}    Sync CM 10.2 repo"
    if [ ! -f $CM/vendor/cm/proprietary/lib/armeabi/libjackpal-androidterm4.so ] && [ ! -f $CM/vendor/cm/proprietary/lib/mips/libjackpal-androidterm4.so ] && [ ! -f $CM/vendor/cm/proprietary/lib/x86/libjackpal-androidterm4.so ]; then
      echo "  ${bldblu}P${txtrst}    Get CM prebuilts"
    fi
    echo "  ${bldblu}2${txtrst}    Build CM 10.2"
    echo "  ${bldblu}3${txtrst}    Push finished build to device"
    echo "  ${bldblu}4${txtrst}    Reboot menu"
    echo "  ${bldblu}5${txtrst}    Pick cherries"
    echo "  ${bldblu}6${txtrst}    View the CM Gerrit"
    echo "  ${bldblu}L${txtrst}    Logcat"
    echo "  ${bldred}C${txtrst}    Clean build directory"
    echo "  ${bldblu}X${txtrst}    Exit"
    echo "${bldblu}$line${txtrst}"
    tput civis
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [Ss]) Init_Repo;;
      [1]) Start_Sync;;
      [2]) Start_Build;;
      [3]) Start_Push;;
      [4]) Reboot_Menu;;
      [5]) Pick_Cherries;;
      [6]) xdg-open http://review.cyanogenmod.org/#/q/status:merged+branch:cm-10.2,n,z ;;
      [Cc]) Ask_Clobber;;
      [Pp]) Get_Prebuilts;;
      [Ll]) Logcat_Menu;;
      [Xx]) clear
        adb kill-server
        echo "${bldblu}Live long and prosper... tristan202${txtrst}"
        echo ""
        tput cnorm
        numlockx off
      break ;;
    esac
  done
  exit 0
}

Main
