#!/bin/bash
# Menu to maintain and build SLIM.
# Written by tristan202. Feel free to use, modify and distribute the script.
# Just remember to give proper credit
#
# tristan202 [ad] gmail.com

me=`basename $0`

# Colorize and add text parameters
txtbld=$(tput bold)             # Bold
bldred=${txtbld}$(tput setaf 1) #  red
bldgrn=${txtbld}$(tput setaf 2) #  green
bldblu=${txtbld}$(tput setaf 4) #  blue
txtrst=$(tput sgr0)             # Reset
line='----------------------------------------'

# Make sure to add a model name
if [ "$#" == "0" ]; then
  echo ""
  echo "Usage: $me {Model name, i.e. yuga|maguro}"
  exit 1
fi

# A few variables
SLIM=$HOME/android/slimkat
DEVICE=$1
OUT=$SLIM/out/target/product/$DEVICE
TRISTAN202=$HOME/android/tristan202
VENDORADD=$TRISTAN202/vendor_slim_torch

# Current time
NOWFULL=$(date +%b-%d-%Y-%H.%M)
NOWDATE=$(date +%b-%d-%Y)
# Rename the Guake tab, end enable numlock
guake -r "Slimkat 4.4"

if [ -x /usr/bin/numlockx ]; then
  /usr/bin/numlockx on
fi

Output() {
  echo "${bldgrn}$(date -d "1970-01-01 UTC $2 seconds") - $1 $OPERATION""ing $3${txtrst}"
}

Duration() {
  local S=$(echo $FINISH_TIME $BEGIN_TIME | awk '{print$1-$2}')
  ((h=S/3600))
  ((m=S%3600/60))
  ((s=S%60))
  printf "$OPERATION""ing took: %dh:%dm:%ds\n" $h $m $s
}

Begin() {
  BEGIN_TIME=$(date +%s)
  Output Begin $BEGIN_TIME "$1"
}

Finish() {
  FINISH_TIME=$(date +%s)
  Output Finished $FINISH_TIME "$1"
  Duration
}

Init_Repo ()
{
  clear
  if [ ! -d $SLIM ]; then
    echo ""
    echo "${bldblu}Setting up SLIM repo...${txtrst}"
    mkdir $SLIM
  fi
  if [ ! -d ~/bin ]; then
    mkdir ~/bin
    PATH=~/bin:$PATH
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
  fi
  if [ ! -f ~/bin/repo ]; then
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    chmod a+x ~/bin/repo
  fi
  cd $SLIM && repo init -u git://github.com/SlimRoms/platform_manifest.git -b kk4.4
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Start_Sync ()
{
  clear
  if [ -d $SLIM ]; then
    echo ""
    OPERATION="Sync"
    Begin
    echo ""
    echo "${bldblu}Syncing repo...${txtrst}"
    cd $SLIM && repo sync
    echo ""
    Finish
  else
    echo ""
    echo "${bldred}Directory does not exist. Check your 'SLIM' variable in line 26.${txtrst}"
    echo ""
    exit 0
  fi
  Sync_End
}

Sync_End ()
{
  echo ""
  echo "${bldblu}Got any cherries to pick?${txtrst}"
  echo -n "Press [${bldgrn}Y${txtrst}] if you do, or [${bldred}N${txtrst}] to return to main menu."
  echo ""
  read -n1 char
  case "$char" in
    [Nn]) Main ;;
    [Yy])  Pick_Cherries ;;
    *)   clear && echo "" && Sync_End ;;
  esac
}

Start_Build ()
{
  clear
  OPERATION="Build"
  files=$(ls $OUT/*.zip* 2> /dev/null | wc -l)
  if [ "$files" != "0" ]; then
    echo "${bldblu}Previous builds detected in 'out' folder. Delete them now?${txtrst}"
    echo -n "Press [${bldgrn}Y${txtrst}] to delete them, or [${bldred}N${txtrst}] to start build without deleting them."
    echo ""
    read -n1 char
    case "$char" in
      [Nn]) Build ;;
      [Yy])  rm $OUT/*.zip* ;;
      *) Start_Build ;;
    esac
  fi
  Build
}

Build ()
{
  clear
  echo ""
  echo "${bldblu}Good, starting build...${txtrst}"
  Begin
  cd $SLIM
  rm -rf out/target/product/$DEVICE/system/build.prop
  wait
  echo ""
  echo "${bldblu}Setting up environment${txtrst}"
  echo ""
  . build/envsetup.sh
  wait
  echo ""
  echo "${bldblu}Brunching device${txtrst}"
  echo ""
  brunch $DEVICE -j2
  Finish
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Reboot_Bootloader ()
{
  clear
  echo ""
  echo "${bldblu}Rebooting to bootloader. Happy flashing.${txtrst}"
    if pidof -x adb > /dev/null
  then
    echo "ADB server already running, proceeding."
    sleep 2
  else
  adb start-server
  fi
  adb reboot bootloader
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  adb kill-server
  Main
}

Start_Clobber ()
{
  clear
  echo ""
  echo "${bldblu}Cleaning build directory...${txtrst}"
  OPERATION="Clean"
  Begin
  cd $SLIM
  make clobber
  Finish
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Pick_Cherries ()
{
  clear
  echo ""
  echo "${bldblu}Picking cherries...${txtrst}"
  OPERATION="Cherrypick"
  tput cnorm
  echo ""
  echo "${bldblu}Copy/paste the project folder, i.e. 'frameworks/base'${txtrst}"
  echo -n ">" && read folder
  echo ""
  echo "${bldblu}Now paste the cherry-pick git link, i.e. 'git fetch <someproject> refs/changes/... && git cherry-pick FETCH_HEAD'${txtrst}"
  echo -n ">" && read cherry
  clear
  echo ""
  Begin
  cd $SLIM/$folder
  CHERRY=${cherry%%??????????????????????????????}
  $CHERRY && git cherry-pick FETCH_HEAD
  Finish
  echo ""
  echo "${bldblu}Got any more cherries to pick?${txtrst}"
  echo -n "Press [${bldgrn}Y${txtrst}] if you do, or [${bldred}N${txtrst}] to return to main menu."
  echo ""
  read -n1 char
  case "$char" in
    [Nn]) Main ;;
    [Yy])  Pick_Cherries ;;
    *)   Pick_Cherries ;;
  esac
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Start_Push ()
{
  clear
  echo "If you haven't done so already, connect your phone to usb now."
  read -p "${bldblu}Press [Enter] to continue...${txtrst}"
  echo ""
  if pidof -x adb > /dev/null
  then
    echo "ADB server already running, proceeding."
    sleep 2
  else
    adb start-server
  fi
  DEVICES=$(adb get-state)
  if [ $DEVICES == "device" ]; then
    FILE=$(find $OUT -type f -name "Slim-*.zip" -printf %f)
    for zip in $FILE
    do
      echo "${bldblu}$line${txtrst}"
      echo ""
      echo "Push to internal or external?"
      echo ""
      echo "  ${bldblu}1${txtrst}    Internal (/sdcard)"
      echo "  ${bldblu}2${txtrst}    External (/ext_card)"
      echo ""
      echo "${bldblu}$line${txtrst}"
      echo -n "${bldblu}  "
      read -n1 answer
      echo "${txtrst}"
      case "$answer" in
        [1]) Push_Int ;;
        [2]) Push_Ext ;;
           *) Start_Push ;;
      esac
    done
  else
    echo ""
    echo "${bldred}Are you completely sure you remembered to plug in both ends of the cable?${txtrst}"
    read -p "${bldblu}Press [Enter] to try again...${txtrst}"
    Start_Push
  fi
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  Main
}

Push_Int ()
{
  FILE=$(find $OUT -type f -name "Slim-*.zip" -printf %f)
  for zip in $FILE
  do
    clear
    OPERATION="Push"
    Begin
    echo ""
    echo "Pushing '$zip' to /sdcard/slim-unofficial-$NOWDATE-tristan202.zip"
    adb push $OUT/$zip /sdcard/slim-unofficial-$NOWDATE-tristan202.zip
    Finish
  done
}

Push_Ext ()
{
  FILE=$(find $OUT -type f -name "Slim-*.zip" -printf %f)
  for zip in $FILE
  do
    clear
    OPERATION="Push"
    Begin
    echo ""
    echo "Pushing '$zip' to /ext_card/slim-unofficial-$NOWDATE-tristan202.zip"
    adb push $OUT/$zip /ext_card/slim-unofficial-$NOWDATE-tristan202.zip
    Finish
  done
}

Reboot_Recovery ()
{
  clear
  echo ""
  echo "${bldblu}Rebooting to recovery. Happy flashing.${txtrst}"
    if pidof -x adb > /dev/null
  then
    echo "ADB server already running, proceeding."
    sleep 2
  else
  adb start-server
  fi
  adb reboot recovery
  read -p "${bldblu}Press [Enter] to return to menu...${txtrst}"
  adb kill-server
  Main
}

Ask_Clobber ()
{
  while true
  do
    clear
    echo ""
    echo "${bldblu}Are you sure you want to do this? It is rarely needed...${txtrst}"
    echo ""
    echo -n "Press [${bldred}Y${txtrst}] to continue, or [${bldgrn}N${txtrst}] to return to main menu."
    read -n1 char
    case "$char" in
      [Nn]) Main ;;
      [Yy]) Start_Clobber ;;
      *) Ask_Clobber ;;
    esac
  done
}

Logcat_Menu ()
{
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "Logcat menu"
    echo ""
    echo "To stop the logcat, press ctrl+z"
    echo "The name of the logfile will be"
    echo "~/logcat-<time-date>.log"
    echo ""
    echo "Select from the following functions"
    echo ""
    echo "  ${bldblu}1${txtrst}    Logcat to file"
    echo "  ${bldblu}2${txtrst}    Live logcat"
    echo "${bldblu}$line${txtrst}"
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [1]) clear && adb logcat >> ~/logcat-$NOWFULL.log;;
      [2]) clear && adb logcat -C;;
    esac
  done
  exit 0
}

Reboot_Menu ()
{
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "Reboot menu"
    echo ""
    echo "Select from the following functions"
    echo ""
    echo "  ${bldblu}1${txtrst}    Reboot"
    echo "  ${bldblu}2${txtrst}    Reboot to recovery"
    echo "  ${bldblu}3${txtrst}    Reboot to bootloader"
    echo "  ${bldblu}4${txtrst}    Return to main menu"
    echo "${bldblu}$line${txtrst}"
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [1]) adb reboot && Main;;
      [2]) Reboot_Recovery;;
      [3]) Reboot_Bootloader;;
      [4]) Main;;
    esac
  done
  exit 0
}

Main ()
{
  clear
  while true
  do
    clear
    echo "${bldblu}$line${txtrst}"
    echo "SLIM maintenance and build script"
    echo ""
    echo "Building ${bldblu}Slimkat 4.4${txtrst} for ${bldblu}$DEVICE${txtrst}"
    echo ""
    echo "Select from the following functions"
    echo ""
    if [ ! -f $SLIM/.repo/manifest.xml ]; then
      echo "  ${bldgrn}S${txtrst}    Set up Slimkat 4.4 repo"
    fi
    echo "  ${bldblu}1${txtrst}    Sync Slimkat 4.4 repo"
    echo "  ${bldblu}2${txtrst}    Build Slimkat 4.4"
    echo "  ${bldblu}3${txtrst}    Push finished build to device"
    echo "  ${bldblu}4${txtrst}    Reboot menu"
    echo "  ${bldblu}5${txtrst}    Pick cherries"
    echo "  ${bldblu}L${txtrst}    Logcat"
    echo "  ${bldred}C${txtrst}    Clean build directory"
    echo "  ${bldblu}X${txtrst}    Exit"
    echo "${bldblu}$line${txtrst}"
    tput civis
    echo -n "  "
    read -n1 answer
    case "$answer" in
      [Ss]) Init_Repo;;
      [1]) Start_Sync;;
      [2]) Start_Build;;
      [3]) Start_Push;;
      [4]) Reboot_Menu;;
      [5]) Pick_Cherries;;
      [Cc]) Ask_Clobber;;
      [Ll]) Logcat_Menu;;
      [Xx]) clear
        adb kill-server
        echo "${bldblu}Live long and prosper... tristan202${txtrst}"
        echo ""
        tput cnorm
	if [ -x /usr/bin/numlockx ]; then
	  /usr/bin/numlockx off
	fi
	break ;;
    esac
  done
  exit 0
}

Main
