#!/bin/bash

fbname=`basename "$1"`
echo -ne "\033]0;Burning $fbname\007"

Output() {
  echo "$(date -d "1970-01-01 UTC $2 seconds") - $1"
}

Duration() {
  local S=$(echo $FINISH_TIME $BEGIN_TIME | awk '{print$1-$2}')
  ((h=S/3600))
  ((m=S%3600/60))
  ((s=S%60))
  printf "Burning took: %dh:%dm:%ds\n" $h $m $s
}

Begin() {
  BEGIN_TIME=$(date +%s)
  Output Begin $BEGIN_TIME "$1"
}

Finish() {
  FINISH_TIME=$(date +%s)
  Output Finished $FINISH_TIME "$1"
  Duration
}

Begin
while ! udisks --show-info /dev/sr0 | grep -c "blank: *1"
do
clear
echo "Waiting for disc."
sleep 1 && clear
echo "Waiting for disc.."
sleep 1 && clear
echo "Waiting for disc..."
sleep 1 && clear
done
clear
echo "Blank disk detected, starting burn."
echo ""
growisofs -speed=2 -dvd-compat -Z /dev/sr0="$1"

#For use with Brasero
#brasero --immediately -i "$1"

# For use with cdrtools
# cdrecord -v speed=4 gracetime=2 driveropts=burnfree -eject -dev=/dev/sr0 -sao "$1"

echo ""
echo "$fbname burned to disc."
echo ""
Finish
paplay ~/bin/woohoo.wav
echo ""
echo "Done!"
    echo "Would you like to delete $fbname?"
    prompt='Press [Y] to delete it, or [N] to quit without deleting it.'
    echo -n "$prompt"
    echo ""
    read -n1 char
    case "$char" in
      [Nn]) echo "" && read -p "Press [Enter] to continue." ;;
      [Yy])  rm "$1"  && echo "" && echo "$fbname deleted" && echo "" && read -p "Press [Enter] to continue." ;;
    esac
