#!/bin/bash

# Script to easily enable/disable output to external monitor/tv.
#
# tristan202 [ad] gmail.com

#The scripts basename
me=`basename $0`

#Query the vga port, and enable if connected.
if [ "$1" = "on" ]; then
	if disper -l | grep "display CRT1" > /dev/null ; then
		#disper -r 1280x768 -c
		xrandr --output LVDS --mode 1366x768 --rate 60 --output CRT1 --mode 1280x768 --pos 0x768 --rate 60
		echo "TV-Out enabled"
	else
		echo "No secondary screen detected."
	fi

#Disable tv-out, and restore screen resolution.
elif [ "$1" = "off" ]; then
	#disper -r 1366x768 -s
	xrandr --output LVDS --mode 1366x768 --rate 60 --output CRT1 --off
	echo "TV-Out disabled"

#Print an error message if no argument is given.
elif [ -z "$1" ]; then
	echo "Usage: $me enable/disable"
fi
