#!/bin/bash

# Script to easily enable/disable output to external monitor/tv.
#
# tristan202 [ad] gmail.com

#The scripts basename
me=`basename $0`

case $1 in
	on)
		#Query the vga port, and enable if connected.
		if xrandr | grep "CRT1 connected" > /dev/null ; then
		xrandr --output LVDS --mode 1366x768 --output CRT1 --mode 1280x768 --below LVDS
		nitrogen --restore
		echo "TV-Out enabled"
			else
				echo "No secondary screen detected."
		fi
	;;
	off)
		#Disable tv-out, and restore screen resolution.
		xrandr --output LVDS --mode 1366x768 --rate 60 --output CRT1 --off
		echo "TV-Out disabled"
	;;
	*)
		echo "Usage: dual {on|off}"
		exit 1
	;;
esac


